### ISSUE TITLE
Lab 4.2 You talkin' to me?, has a significant error in the problem statement

### ISSUE THREAD

**Issue by jpfasano** [TEALSK12/introduction-to-computer-science#433]
This [lab](https://tealsk12.github.io/introduction-to-computer-science/lab_42.md.html) requires students to generate a custom reporter block named **verb phrase** consisting of _adverb, prpositional phrase_.  The **verb phrase** should be _adverb, verb, prepositional phrase_.   As the lab is currently written, the generated sentences will not have verbs.
![Screenshot 2022-12-13 110801](https://user-images.githubusercontent.com/9619225/207384640-3a80bf38-fab1-4577-8fad-19811a5f3cf0.png)

**Comment by jinglebiscuits** [comment]
This has been fixed in the markdown file, but the pdf is still wrong. The pdf needs to be updated.
There's a second error in this pdf directly below the highlighted Construction in @jpfasano 's image. Sentence should be `noun phrase, verb phrase` instead of `noun[COMMA] phrase, verb phrase. This error is also fixed in the .md file.
